"""Build a Croissant JSON-LD document from episode files.

Croissant (MLCommons, https://mlcommons.org/working-groups/data/croissant/) is the
ML-dataset metadata standard: schema.org-based JSON-LD, natively indexed by
Hugging Face, Kaggle, OpenML, and Google Dataset Search. An episode corpus that
ships ``croissant.json`` is discoverable by every major dataset search surface
for free.

Vendored spec version implemented here:

    Croissant 1.1  --  https://docs.mlcommons.org/croissant/docs/croissant-spec-1.1.html
    Pinned 2026-08-31 (MLCommons announcement 2026-02-12). The Dataset /
    Distribution / RecordSet / Field / Data layers follow the 1.1 vocabulary,
    and `dct:conformsTo` declares the versioned spec URI
    `http://mlcommons.org/croissant/1.1`. 1.1 adds machine-actionable
    provenance (W3C PROV via `prov:` in the JSON-LD context and `cr:annotation`
    / `equivalentProperty` for external-vocabulary linking), which is exactly
    what the W1.3 PROV-O mapping below is emitted as. If MLCommons publishes a
    newer minor that changes these keys, re-pin and update the structural
    self-tests in tests/test_croissant.py.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from .check_episodes import check_episodes
from .validate import DocumentKind

__all__ = [
    "CROISSANT_VERSION",
    "CROISSANT_SPEC_URL",
    "CROISSANT_CONFORMS_URI",
    "ExportOptions",
    "ProvenanceMappingError",
    "PROV_MAPPING",
    "build_croissant",
    "croissant_field",
    "provenance_to_prov",
]

CROISSANT_VERSION = "1.1"
CROISSANT_SPEC_URL = "https://docs.mlcommons.org/croissant/docs/croissant-spec-1.1.html"
CROISSANT_CONFORMS_URI = "http://mlcommons.org/croissant/1.1"
CROISSANT_CONTEXT = "http://mlcommons.org/croissant/1.1"

# Map each episode `provenance` value to the W3C PROV-O term, after reading the
# actual PROV-O definitions (https://www.w3.org/TR/prov-o/, 2013, read
# 2026-08-31):
#   * `prov:wasDerivedFrom` — "An entity is derived from an entity", i.e. one
#     entity is a revision of, or was based on, another. A `retrospective`
#     episode (recalled from a prior tapeout, no run artifact) is a record
#     *derived from* a prior design state, so this is the nearest fit for the
#     recollection-without-run case. The "expert recollection agent" aspect is
#     better captured by `prov:wasAttributedTo`, noted in HANDOFF as a
#     spec-drift nuance: the spec's sketch is close but not exact.
#   * `prov:wasGeneratedBy` — "An entity is generated by an activity". A
#     `reproduced` episode is the *output of a run activity* whose tool/PDK
#     versions come from the run-manifest, so this is a correct fit.
#   * `synthetic-fixture` — schema-valid validator food, NOT data. No PROV term
#     applies; it is marked non-evidential (`edi:non_evidential`, a private EDI
#     extension term, not a W3C PROV term), so a consumer can see at a glance
#     that this row is not evidence of anything.
PROV_MAPPING: dict[str, str] = {
    "retrospective": "prov:wasDerivedFrom",
    "reproduced": "prov:wasGeneratedBy",
    "synthetic-fixture": "edi:non_evidential",
}


class ProvenanceMappingError(ValueError):
    """An episode `provenance` value cannot be mapped to a PROV-O term.

    Distinct from every schema-validation error code, so a test can tell a
    wrong-provenance-mapping failure apart from any other.
    """

    code = "E_PROV_UNMAPPED_PROVENANCE"


def provenance_to_prov(provenance: str) -> str:
    """Return the PROV-O term for an episode ``provenance`` value.

    Raises :class:`ProvenanceMappingError` (code ``E_PROV_UNMAPPED_PROVENANCE``)
    for a value that has no mapping — the mutation-test surface.
    """
    try:
        return PROV_MAPPING[provenance]
    except KeyError:
        raise ProvenanceMappingError(f"provenance {provenance!r} has no PROV-O mapping") from None


# The episode document kind this exporter consumes.
_EPISODE_KIND: DocumentKind = "episode"


@dataclass(frozen=True)
class _Field:
    name: str
    description: str
    data_type: str  # a schema.org DataType, e.g. "Text", "Number", "Integer"
    source: str  # JSON path into the episode document


# The mapping from episode fields to Croissant RecordSet columns. ``source`` is
# the JSON pointer-ish path this module reads from each admitted episode. These
# are the mechanical, structural fields -- the judgment fields (hypothesis,
# rationale) are intentionally included as Text so the dataset is faithful, but
# the DATASET_CARD keeps any interpretive claims as TODO(expert).
_RECORD_FIELDS: tuple[_Field, ...] = (
    _Field("episode_id", "Stable unique episode id (EP-<domain>-<nnn>).", "Text", "episode_id"),
    _Field("provenance", "retrospective | reproduced | synthetic-fixture.", "Text", "provenance"),
    _Field("design_name", "Design under decision.", "Text", "design/name"),
    _Field("design_pdk", "Process design kit / node.", "Text", "design/pdk"),
    _Field(
        "design_rtl_commit", "Pinned RTL commit (reproduced episodes).", "Text", "design/rtl_commit"
    ),
    _Field(
        "design_pdk_commit",
        "Pinned PDK commit (reproduced episodes).",
        "Text",
        "design/pdk_commit",
    ),
    _Field("failure_class", "FAIL_* / SDC_BUDGET class of the failure.", "Text", "failure_class"),
    _Field(
        "observation_metric",
        "Metric name with unit suffix, e.g. wns_ns.",
        "Text",
        "observation/metric",
    ),
    _Field("observation_value", "Observed value (number or string).", "Text", "observation/value"),
    _Field("observation_target", "Target value.", "Text", "observation/target"),
    _Field(
        "observation_severity",
        "blocking | degrading | cosmetic.",
        "Text",
        "observation/severity",
    ),
    _Field("hypothesis", "Expert causal reading of the observation.", "Text", "hypothesis"),
    _Field(
        "expert_assessment",
        "preferred | acceptable | regretted | inconclusive.",
        "Text",
        "expert_assessment",
    ),
    _Field(
        "rationale",
        "Why the chosen intervention beat the others.",
        "Text",
        "rationale",
    ),
    _Field("confidence", "Expert confidence in [0, 1].", "Number", "confidence"),
    _Field(
        "chosen_parameter",
        "Parameter/knob changed by the chosen intervention.",
        "Text",
        "chosen_intervention/parameter",
    ),
    _Field("chosen_before", "Parameter value before.", "Text", "chosen_intervention/before"),
    _Field("chosen_after", "Parameter value after.", "Text", "chosen_intervention/after"),
    _Field(
        "prior_stage",
        "Flow stage before the intervention.",
        "Text",
        "prior_state/stage",
    ),
    _Field(
        "post_stage",
        "Flow stage after the intervention.",
        "Text",
        "post_state/stage",
    ),
    _Field(
        "run_manifest_ref",
        "Reference to the backing run-manifest (reproduced episodes).",
        "Text",
        "run_manifest_ref",
    ),
)


@dataclass
class ExportOptions:
    """Tunables for :func:`build_croissant`."""

    name: str = "edi-episodes"
    description: str = (
        "Engineering-decision episodes: one recorded expert decision per physical-"
        "design or proving flow, with the state before, the observation, the "
        "candidates considered and rejected, the chosen intervention, and the "
        "expert's assessment."
    )
    # A stable identifier for the dataset. HF/Kaggle/OpenML key off this.
    url: str = "https://github.com/PostOakLabs/engineering-decision-schema"
    license: str = "CC-BY-4.0"
    include_drafts: bool = False
    # Extra provenance stamped into the dataset metadata (e.g. the schema version).
    extra_keywords: tuple[str, ...] = ()

    def as_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "description": self.description,
            "url": self.url,
            "license": self.license,
            "include_drafts": self.include_drafts,
            "extra_keywords": list(self.extra_keywords),
        }


def _dig(document: Mapping[str, Any], path: str) -> Any:
    """Read a ``/``-separated path out of ``document``, tolerating missing nodes."""
    node: Any = document
    for part in path.split("/"):
        if not isinstance(node, Mapping) or part not in node:
            return None
        node = node[part]
    return node


def croissant_field(field: _Field) -> dict[str, Any]:
    """Render one :class:`_Field` as a Croissant ``Field`` JSON object."""
    return {
        "@type": "cr:Field",
        "@id": f"episodes/{field.name}",
        "name": field.name,
        "description": field.description,
        "dataType": field.data_type,
        "source": {
            "@type": "cr:JsonPath",
            # The RecordSet is built directly from in-memory episode dicts, so the
            # JSONPath is relative to one episode document.
            "container": "cr:Episode",
            "jsonPath": f"$.{field.source}",
        },
    }


@dataclass
class _BuildSummary:
    included: int = 0
    excluded_drafts: int = 0
    schema_invalid: int = 0
    unreadable: int = 0
    enumerations: dict[str, set[str]] = field(default_factory=dict)


def build_croissant(
    directory: str,
    options: ExportOptions | None = None,
) -> tuple[dict[str, Any], _BuildSummary]:
    """Build a Croissant JSON-LD document from the episode files in ``directory``.

    Returns ``(document, summary)``. ``document`` is the Croissant dataset as a
    plain ``dict`` (ready for ``json.dumps``); ``summary`` reports how many
    episodes were included, excluded as drafts, or rejected as schema-invalid.

    Drafts (TODO-marked skeletons, synthetic fixtures) are excluded unless
    ``options.include_drafts`` is true -- a discovery surface must never index a
    TODO skeleton as data.
    """
    options = options or ExportOptions()
    results, unreadable = check_episodes(directory, strict=not options.include_drafts)

    summary = _BuildSummary(unreadable=len(unreadable))
    rows: list[dict[str, Any]] = []
    enumerations: dict[str, set[str]] = {}

    def track_enum(key: str, value: Any) -> None:
        if value is None or not isinstance(value, str):
            return
        enumerations.setdefault(key, set()).add(value)

    for result in results:
        if not result.included:
            if result.valid:
                summary.excluded_drafts += 1
            else:
                summary.schema_invalid += 1
            continue
        summary.included += 1
        # Re-read the document to build the row. check_episodes already parsed it;
        # re-reading is cheaper than threading the document through CheckResult
        # and keeps the two modules decoupled.
        from pathlib import Path

        document = json.loads(Path(result.path).read_text(encoding="utf-8"))

        row: dict[str, Any] = {}
        for f in _RECORD_FIELDS:
            value = _dig(document, f.source)
            # Croissant wants real types where the schema gives them. Numbers stay
            # numbers; everything else is emitted as Text (stringified only if it
            # is not already a str, so a numeric observation_value stays a string
            # by design -- the schema types value as number|string).
            if f.data_type == "Number" and isinstance(value, (int, float)):
                row[f.name] = value
            elif value is None:
                row[f.name] = None
            elif isinstance(value, str):
                row[f.name] = value
            else:
                row[f.name] = json.dumps(value)
        rows.append(row)

        track_enum("provenance", _dig(document, "provenance"))
        track_enum("failure_class", _dig(document, "failure_class"))

    summary.enumerations = enumerations

    field_defs = [croissant_field(f) for f in _RECORD_FIELDS]
    provenance_terms = sorted(enumerations.get("provenance", set()))
    failure_terms = sorted(enumerations.get("failure_class", set()))

    # Content hash of the admitted-rows array (the SAME list object the
    # recordSet includes below). Compact canonical serialization; freshness-
    # compatible by construction (a regen recomputes it deterministically),
    # no external fetch, and never a hash of the croissant document itself.
    rows_sha256 = hashlib.sha256(
        json.dumps(rows, separators=(",", ":"), sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()

    dataset: dict[str, Any] = {
        "@context": {
            "@language": "en",
            "@vocab": "https://schema.org/",
            "sc": "https://schema.org/",
            "cr": "http://mlcommons.org/croissant/",
            "prov": "http://www.w3.org/ns/prov#",
            "edi": "https://postoaklabs.github.io/engineering-decision-schema/",
            "dct": "http://purl.org/dc/terms/",
            "annotation": "cr:annotation",
            "equivalentProperty": "cr:equivalentProperty",
            "data": {"@id": "cr:data", "@type": "@json"},
            "data_extract": {"@id": "cr:dataExtract", "@type": "@json"},
        },
        "@type": "Dataset",
        "@id": options.url,
        "name": options.name,
        "description": options.description,
        "url": options.url,
        "license": options.license,
        "version": CROISSANT_VERSION,
        # Croissant 1.1 declares the versioned spec URI here. This is the
        # extension mechanism the W1.3 PROV-O mapping uses: 1.1's
        # `dct:conformsTo` + external vocabularies rather than ad-hoc keys.
        "conformsTo": CROISSANT_CONFORMS_URI,
        "datePublished": datetime.now(UTC).strftime("%Y-%m-%d"),
        "keywords": [
            "engineering-decisions",
            "physical-design",
            "zero-knowledge",
            "provenance",
            *options.extra_keywords,
        ],
        "distribution": [
            {
                # Croissant distributions are FileObject/FileSet nodes;
                # `cr:Distribution` is not a valid @type and the official
                # mlcroissant validator rejects it (EDI-CROISSANT-FIX-1).
                # encodingFormat/contentUrl live directly on the node (not
                # under a `data` wrapper) because the validator requires
                # them as mandatory FileObject properties (FIX-2).
                "@type": "https://schema.org/FileObject",
                "@id": "episodes-dist",
                "name": "episodes",
                "encodingFormat": "application/json",
                "contentUrl": f"{options.url}/tree/main/episodes",
                "sha256": rows_sha256,
            }
        ],
        "recordSet": [
            {
                "@type": "cr:RecordSet",
                "@id": "episodes",
                "name": "episodes",
                "description": "One row per admitted engineering-decision episode.",
                "data": {
                    "encodingFormat": "application/json",
                    "includes": rows,
                },
                "field": field_defs,
                # Enumerations let consumers facet. They are derived from the
                # admitted rows, so an empty corpus yields empty term lists rather
                # than a fabricated vocabulary.
                "enumeration": _build_enumerations(provenance_terms, failure_terms),
                # The W1.3 PROV-O mapping, emitted as JSON-LD so corpus governance
                # is machine-auditable. Each provenance value is linked, via the
                # 1.1 external-vocabulary mechanism, to the PROV-O term it was
                # judged to express; the synthetic-fixture row is marked
                # non-evidential (an EDI extension term, not a W3C PROV term).
                "annotation": _build_prov_annotation(),
            }
        ],
    }

    return dataset, summary


def _build_prov_annotation() -> list[dict[str, Any]]:
    """The PROV-O mapping as a Croissant 1.1 ``annotation`` block."""
    return [
        {
            "@type": "cr:Field",
            "@id": "episodes/provenance_mapping",
            "name": "provenance_mapping",
            "description": (
                "EDI episode `provenance` -> W3C PROV-O term, per W1.3. "
                "synthetic-fixture is non-evidential."
            ),
            "equivalentProperty": "prov:derivation",
            "subField": [
                {
                    "@type": "cr:Field",
                    "@id": f"episodes/provenance_mapping/{value}",
                    "name": value,
                    "description": (
                        "episode provenance value maps to PROV-O term "
                        f"{term}"
                        + (
                            " (marked non-evidential: schema-valid validator food, not data)"
                            if term == "edi:non_evidential"
                            else ""
                        )
                    ),
                    "dataType": "prov:Entity",
                    "value": {"term": term},
                }
                for value, term in PROV_MAPPING.items()
            ],
        }
    ]


def _build_enumerations(
    provenance_terms: Sequence[str],
    failure_terms: Sequence[str],
) -> list[dict[str, Any]]:
    enumerations: list[dict[str, Any]] = []
    if provenance_terms:
        enumerations.append(
            {
                "@type": "cr:Enumeration",
                "@id": "provenance-enum",
                "name": "provenance",
                "terms": [
                    {"@type": "cr:Term", "name": term, "description": f"provenance = {term}"}
                    for term in provenance_terms
                ],
            }
        )
    if failure_terms:
        enumerations.append(
            {
                "@type": "cr:Enumeration",
                "@id": "failure-class-enum",
                "name": "failure_class",
                "terms": [
                    {"@type": "cr:Term", "name": term, "description": f"failure_class = {term}"}
                    for term in failure_terms
                ],
            }
        )
    return enumerations
